remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Info about ...
description: This, poekwdpoqkpokp qw pqowp wpd peokapjofp[aewri[ wi oiew0io
show_downloads: false
google_analytics: [Your Google Analytics tracking ID]

