title: Дополнительная информация о деятельности Скрипник П.М. 
description: Многие пациенты жалуются на непрофессиональные и даже опасные действия "костоправа" Петра Скрипника
show_downloads: false
google_analytics:
<!-- theme: jekyll-theme-tactile  -->
